version: '3.1'
services:
  turbine-stream-service:
    image: thetinydev/turbine-stream-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - custom_network
networks:
  custom_network:
